### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by RoseLucy** [ngoc199/watermark-image-project#1]
You are right, but the watermarked photos I got are all cut. How can I get a complete watermarked image?

**Comment by ngoc199** [comment]
Thank you for your question, @RoseLucy !
But I'm very sorry you too.
I don't own this project or the idea behind it.
This repo is just a mistake when I first using Github. I forgot to fork it and created a new one accidentally.
I will delete this repo to preserve the real authority for sure.
And if you want to get complete watermarked image, which will answer your question, you should contact the real author. Here is the real repo: https://github.com/rohitrango/automatic-watermark-detection
I hope you will find the answer.
